version: '3.8'

# For mount and volumes, see: https://docs.docker.com/storage/
# 
# There are several options about the user data
# 
# 1. 
#   create a new folder under /opt/ or /usr/local/
#
#   configurations  ->  singlishwords/etc/config.yaml
#   exeutable       ->  singlishwords/bin/
#   database        ->  singlishwords/data/
#   frontend        ->  singlishwords/nginx/
# 
# 2.
#   follow Filesystem Hierarchy Standard suggest (ref: https://linux.die.net/man/7/hier)
# 
#   config web      ->  /usr/local/etc/singlishwords/web
#   database        ->  /var/local/singlishwords/mysql
#   frontend        ->  /var/local/singlishwords/www
#
#   app log         ->  /var/local/singlishwords/log/web
#   
#   nginx log       ->  /var/local/singlishwords/log/nginx
#   config nginx    ->  /usr/local/etc/singlishwords/nginx/conf.d
#   ssl cert        ->  /etc/letsencrypt
# 

# ports:
# - "8080:8080" # outer:inner
services:
    redis:
        build: ./redis/
        image: singlishwords_redis
        volumes:
            - ./mnt/config/redis.conf:/usr/local/etc/redis/redis.conf
    mysql:
        platform: linux/x86_64
        build: ./mysql/
        image: "singlishwords_mysql"
        volumes:
            - singlishwords-mysql:/var/lib/mysql
            # - ./mnt/mysql-init.d/:/docker-entrypoint-initdb.d/
            - ./mnt/config/mysql-conf.d/:/etc/mysql/mysql.conf.d/
            
        environment: # will change to env files or envs later
            - MYSQL_ROOT_PASSWORD=d8sx9anc8asx
            - MYSQL_DATABASE=singlishwords
            - MYSQL_USER=csqsiew
            - MYSQL_PASSWORD=u98x7v89asx
    singlishwords_app:
        build: ./backend/
        image: singlishwords_app
        volumes:
            - ./mnt/log/singlishwords:/var/log/singlishwords
            - ./mnt/config/config.yaml:/opt/singlishwords/config.yaml
        depends_on:
            - redis
            - mysql
    nginx:
        build: ./frontend
        restart: always
        image: singlishwords_nginx
        # image: "nginx:1.21-alpine"
        restart: always
        ports:
            - 80:80
            - 443:443
            - 8080:8080
        depends_on:
            - singlishwords_app
            - jupyter
        volumes:
        # below are nginx part
            - ./mnt/config/nginx-conf/nginx.conf:/etc/nginx/nginx.conf
            - ./mnt/config/nginx-conf/conf.d:/etc/nginx/conf.d
            # - ./mnt/config/nginx-conf.d:/etc/nginx/conf.d
            - ./mnt/log/nginx:/tmp/nginx
            # - /var/local/singlishwords/log/nginx:/var/log/nginx
            
            - ./mnt/html:/usr/share/nginx/html
            #- frontend-static:/usr/share/nginx/html
            # - /etc/letsencrypt:/etc/letsencrypt
    jupyter:
        build: ./management
        restart: always
        image: singlishwords_management
        command: start-notebook.sh --NotebookApp.password='sha1:c2b7b1d3a592:fd9ce75de418a2119291772cac9d5b629a3b50de'
        ports:
            - 8888:8888
        volumes:
            - ./mnt/jupyter-data:/home/jovyan/work/export-data
volumes:
  #frontend-static:
    singlishwords-mysql:
